layout_spectrum: 0.2061404
color:
  saturation: 0.1390978
  brandStrength: 0.8850275
  lightness: 0.127193
  rhythmicContrast: 0.8214957
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.3878446
name: Photos and Other Interesting Things
